apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-test
  labels:
    bucket: aws
spec:
  forProvider:
    region: eu-west-1
  providerConfigRef:
    name: default