apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-backup
spec:
  compositeTypeRef:
    apiVersion: custom-api.example.org/v1alpha1
    kind: XDatabase
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          labels:
            bucket: aws
        spec:
          forProvider:
            region: "eu-west-1" 
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.bucketname
          toFieldPath: base.metadata.name